### ISSUE TITLE
Installation of OpenCV

### ISSUE THREAD

**Issue by kanza-ali** [xingyizhou/pytorch-pose-hg-3d#10]
Hi,
Shall I install openCV by following all these instructions: https://www.learnopencv.com/install-opencv3-on-ubuntu/

**Comment by salihkaragoz** [comment]
this is the easier way...

https://asciinema.org/a/WHfIDk8R6T5ORjXTyENIFQNk9

**Comment by xingyizhou** [comment]
I used `conda install --channel https://conda.anaconda.org/menpo opencv`. I recommend using Anocanda python for this project.
