### ISSUE TITLE
Testing 

### ISSUE THREAD

**Issue by kanza-ali** [xingyizhou/pytorch-pose-hg-3d#13]
Testing
Download our pre-trained model and move it to models.
Run python demo.py -demo /path/to/image [-loadModel /path/to/image].

Kindly please define again how to run testing side. I have downloaded the pre-trained model and moved to models folder. Then I have to run demo.py which is in src folder? Am I right?

**Comment by xingyizhou** [comment]
Yes, in `src` folder, run `python demo.py -demo /path/to/image [-loadModel /path/to/image]`.

**Comment by XinyuZhou-1014** [comment]
It seems that directly put model in src/ is a better idea, because of the code 
`    model = torch.load('hgreg-3d.pth').cuda()` in demo.py line 15 [https://github.com/xingyizhou/pytorch-pose-hg-3d/blob/84ad44e7a8aa15307b9a371ce85b3dee8d5ad2dc/src/demo.py#L15](url)

**Comment by kanza-ali** [comment]
I dont know but demo.py is not working and giving error. 


![error](https://user-images.githubusercontent.com/33715985/38715716-c8c1d87a-3f17-11e8-8931-d6be7d5d304a.png)

**Comment by xingyizhou** [comment]
It seems a pytorch installation issue. Please check the pytorch homepage.

**Comment by kanza-ali** [comment]
Thank you so much for all your posts and help.

But still, I am unable solve the issue. Did you make this using Python 2.7?

**Comment by xingyizhou** [comment]
Hi, 
  I have only tested my model in python 2. Python 3 is not supported yet. [here](https://github.com/xingyizhou/pytorch-pose-hg-3d/pull/1) is a python3 compactable version (not tested) which you can train the model yourself.

**Comment by xingyizhou** [comment]
Thanks @kanza-ali !

**Comment by bilawal-mahmood** [comment]
![image](https://user-images.githubusercontent.com/39480452/40296049-910d9d2a-5d16-11e8-8511-1877d25096da.png)

I am still getting this error as i change the code for python 3. can you help @kanza-ali

**Comment by bilawal-mahmood** [comment]
'ascii' codec can't decode byte 0xc3 in position 13: ordinal not in range(128)
I am still getting this error. can someone help me solve this. I am using windows and python 2 does not have pytorch. not even for virtual enviroment
