### ISSUE TITLE
H3.6M preprocessing code

### ISSUE THREAD

**Issue by bloodymeli** [xingyizhou/pytorch-pose-hg-3d#19]
Hi,

I was wondering if you can share (possibly privately) the preprocessing code that was used to obtain the preprocessed H3.6M figures and positions.

Thanks!

**Comment by xingyizhou** [comment]
ok

**Comment by Hellomodo** [comment]
Hi，xingyizhou.

Do your have the plan to add the preprocessing code in the repository?
If not, can you share the preprocessing  code privately with me too?

Thanks!

**Comment by xingyizhou** [comment]
Hi Hellomodo, 
  Sorry for the late reply. The data preprocessing code was shared by other researchers, and I am not able to reproduce it or maintain it. So I decide not to include that part in this repo. Please give me your email if you want a private copy.

**Comment by Hellomodo** [comment]
2120171034@bit.edu.cn
Thanks !

**Comment by bloodymeli** [comment]
Hi,
Can you please also share the code with me (tkhnhruo@gmail.com)?

Thanks!

**Comment by neilyoyoyoyo** [comment]
Hi Xingyi,
Could you also send me a private copy of preprocessing code(liqi@ict.ac.cn)?

Thanks!

**Comment by xingyizhou** [comment]
Hi all, 
  Sorry for the inconvenience, I have now uploaded the code to https://drive.google.com/file/d/1erVCGll5OwCC0-CW513rSFtH9WDtqQ2Q/view?usp=sharing . However, I am not 100% familiar with this code so I might not be able to maintain it. But if you have any specific logistic questions regarding to the data pre-processing, feel free to ask me.

**Comment by AlbertLZG** [comment]
Hi Xingyi,
I have original human3.6m data such as videos and annotations. I want to process the data to the same format with you using the supplied preprocessing code above. However, I have not the official human3.6m dataset toolkit, and the preprocessing code doesn't work. Can you send me the official toolkit to me? Thank you~

**Comment by xinghuokang** [comment]
Hi, AlbertLZG, Could you share your datasets for me with network disk link?
