### ISSUE TITLE
pose estimation in video

### ISSUE THREAD

**Issue by bilawal-mahmood** [xingyizhou/pytorch-pose-hg-3d#23]
Is this code work for video? I give a video to code. it is giving following error: 
Traceback (most recent call last):
  File "demo.py", line 31, in <module>
    main()
  File "demo.py", line 17, in main
    input = torch.from_numpy(img.transpose(2, 0, 1)).float() / 256.
AttributeError: 'NoneType' object has no attribute 'transpose'

**Comment by xingyizhou** [comment]
No.

**Comment by Easyfeng222** [comment]
@xingyizhou when I running :python demo.py -demo /home/feng/pytorch-pose-hg-3d/demo
always raise this problem.Thanks for your help
Traceback (most recent call last):
  File "demo.py", line 35, in <module>
    main()
  File "demo.py", line 20, in main
    input = torch.from_numpy(img.transpose(2, 0, 1)).float() / 256.
AttributeError: 'NoneType' object has no attribute 'transpose'
