### ISSUE TITLE
Missing files of your pre-processed Human3.6M dataset？

### ISSUE THREAD

**Issue by gdwei** [xingyizhou/pytorch-pose-hg-3d#24]
Hello！ I find that there is an empty folder in your pre-processed Human3.6M dataset, which is the sub folder 's_11_act_02_subact_02_ca_01'. Could you please check and update the resource？

**Comment by xingyizhou** [comment]
Hi, 
  This file is missing from the original H36M dataset. Most papers on this dataset just ignore this sequence.

**Comment by gdwei** [comment]
Got it, thanks a lot!
