### ISSUE TITLE
test demo problem

### ISSUE THREAD

**Issue by hamburgerBear** [xingyizhou/pytorch-pose-hg-3d#25]
Hi, 
thanks for your code, but I have a problem when I run to demo,

(Human_Pose) gaojie@ubuntu:~$ cd human_pose/pytorch-pose-hg-3d/
data/       .git/       images/     readme.md   
exp/        .gitignore  LICENSE     src/        
(Human_Pose) gaojie@ubuntu:~$ cd human_pose/pytorch-pose-hg-3d/src/
(Human_Pose) gaojie@ubuntu:~/human_pose/pytorch-pose-hg-3d/src$ cd models/
(Human_Pose) gaojie@ubuntu:~/human_pose/pytorch-pose-hg-3d/src/models$ ls
hg_3d.py  hgreg-3d.pth	__init__.py  layers
(Human_Pose) gaojie@ubuntu:~/human_pose/pytorch-pose-hg-3d/src/models$ cd ..
(Human_Pose) gaojie@ubuntu:~/human_pose/pytorch-pose-hg-3d/src$ ls
datasets  demo.py  models   __pycache__  tools	   utils
debug	  main.py  opts.py  ref.py	 train.py
(Human_Pose) gaojie@ubuntu:~/human_pose/pytorch-pose-hg-3d/src$ python demo.py -demo /path/to/image [-loadModel /path/to/image]
usage: demo.py [-h] [-expID EXPID] [-test] [-DEBUG DEBUG] [-demo DEMO]
               [-loadModel LOADMODEL] [-nFeats NFEATS] [-nStack NSTACK]
               [-nModules NMODULES] [-LR LR] [-dropLR DROPLR]
               [-nEpochs NEPOCHS] [-valIntervals VALINTERVALS]
               [-trainBatch TRAINBATCH] [-nRegModules NREGMODULES]
               [-ratio3D RATIO3D] [-regWeight REGWEIGHT]
               [-varWeight VARWEIGHT]
demo.py: error: unrecognized arguments: [-loadModel /path/to/image]
(Human_Pose) gaojie@ubuntu:~/human_pose/pytorch-pose-hg-3d/src$

**Comment by xingyizhou** [comment]
How about trying `python demo.py -demo images/h36m_1214.png`?
