### ISSUE TITLE
MPJPE using the ground truth heatmaps is 17-18

### ISSUE THREAD

**Issue by Naman-ntc** [xingyizhou/pytorch-pose-hg-3d#26]
Hi,
If we try to evaluate MPJPE using the ground truth heatmaps and ground truth z coordinates that are used for regressing then we get it about 17/18.
I think this is because of the perspective projections and the average human bone length ration that is used, but 17/18 is pretty high right?
Any opinions??

**Comment by xingyizhou** [comment]
Hi Naman, 
  Thanks for reporting the number! This is expected, and as you noted, both using parallel projection and using average bone length contributes to the error. But currently, I don't have more suggestions for this. Using parallel projection is a big simplification to the problem (i.e., enabling us to directly apply the 2D detector) and I would say it worth the accuracy trade-off. You can definitely add any other post-processing for a better bone length, e.g., leverage the bbox size cue to determine a better scale. On the other hand, 17/18mm is not that unacceptable, which is only the width of a finger in an actual human body.

**Comment by Naman-ntc** [comment]
Hmm yeah correct, though there should be some standardization on this right, since state of art now reaching about 50..!
Anyways closing this, feel free to open or discuss
