### ISSUE TITLE
How to mapping from xy in joint_2d to x'y' in  joint_3d_mono?

### ISSUE THREAD

**Issue by Fangyh09** [xingyizhou/pytorch-pose-hg-3d#27]
Hi, is there any relationship between x,y in pts and x,y in pts_3d_mono?  
The model output x,y is in pts, but the ground truth is in pts_3d_mono. So I want to figure out whether there is a mapping. Thanks!
https://github.com/xingyizhou/pytorch-pose-hg-3d/blob/84ad44e7a8aa15307b9a371ce85b3dee8d5ad2dc/src/datasets/h36m.py#L40-L43

**Comment by xingyizhou** [comment]
Hi, 
  This is a good question. The detailed transformation code from image xy to world xy is here https://github.com/xingyizhou/pytorch-pose-hg-3d/blob/master/src/utils/eval.py#L70, or a more detailed explanation at https://github.com/xingyizhou/pose-hg-3d/issues/3 . Also, we provide the detailed projection formulation at Section 3.2 of https://arxiv.org/pdf/1803.09331.pdf.

**Comment by Fangyh09** [comment]
Thanks @xingyizhou 
I want to know that during evaluation whether we could use the extrinsic parameters or not?

**Comment by xingyizhou** [comment]
Yes, you can use camera parameters to perform the full perspective projection. However, the depth of the root should be known to resolve the scale-depth ambiguity.

**Comment by Fangyh09** [comment]
@xingyizhou         
It uses gt `meta[i, root]` in L84, so the error is relative error instead of absolute error?
I think the difference between protocol I and protocol II is the `procruste` instead of using gt `meta[i, root]`. Is it right? Thanks~
https://github.com/xingyizhou/pytorch-pose-hg-3d/blob/84ad44e7a8aa15307b9a371ce85b3dee8d5ad2dc/src/utils/eval.py#L84

**Comment by xingyizhou** [comment]
Hi, 
  Sorry for the very delayed reply. I think all evaluations on H36M are based on relative depth. You can check the official [H36M ECCV Challenge](http://vision.imar.ro/human3.6m/challenge_open.php) data and its evaluation script.
