### ISSUE TITLE
An question about average sum-of-skeleton-length.

### ISSUE THREAD

**Issue by JincanDeng** [xingyizhou/pytorch-pose-hg-3d#3]
Hello, xingyizhou.
I am interseted about this project and I have a question about how to compute the average sum-of-skeleton-length.
According to your paper, it is calculated over all the training subjects. But as we all know, the skeleton length difference between different people is huge. For example, a male's skeleton length is longer than a female's in average.
So when you calaulate the MPJPE over the validation dataset, how could you ensure this average skeleton-length is suitable for the subjects, S9 and S11?
Waiting for your answer.

**Comment by xingyizhou** [comment]
Hi Jincan, 
  Thanks for your interests. Using average is the best way we can do when the testing scale is totally unknown. Luckily it works for Human 3.6M, as is also don in the Sparseness meets deepness paper. This average is intended only for Human 3.6M evaluation. For more general in-the-wild pose estimation, you will need a post-processing of the scale.

**Comment by JincanDeng** [comment]
Thanks for your answer very much.
