### ISSUE TITLE
demo error 

### ISSUE THREAD

**Issue by tsly123** [xingyizhou/pytorch-pose-hg-3d#31]
Hi,
Thank you for your work.
I am facing a error while running the demo as shown below. In addition, it took around 5mins to produce the error output.

![image](https://user-images.githubusercontent.com/35265385/42683620-d3d18fb4-86c8-11e8-9026-a67ebb139afe.png)

I have install all the required packages.

**Comment by tsly123** [comment]
Thank @xingyizhou 
It's working now but the processing time for my 1080 is around 5 mins/image. During the process, I use `nvidia-smi` to check whether the GPU work or not. The code does not use GPU resource. Is it an error or just something wrong with my machine?

**Comment by xingyizhou** [comment]
Hi, 
  Sorry for the late reply. The code should run in GPU if set up correctly. 5 mins look un-reasonable even in CPU. Could you debug which line the code is stuck on? If it is `model = torch.load('hgreg-3d.pth').cuda()`, the problem might be the cudnn version doesn't fit your GPU, you should change to anther pytorch version  (https://pytorch.org/previous-versions/).
