### ISSUE TITLE
Question：result of stage1 model to estimate 3d depth is different?

### ISSUE THREAD

**Issue by xinghuokang** [xingyizhou/pytorch-pose-hg-3d#44]
Hello, Zhou, 
     I trained 2D Hourglass Module by your code with 60 epoch, when I was training stage2, the output of depth regress module is very large at the beginning(such as [5000, 122, -13984 ...] and so on) ; But when I used model_60.th you have provided,  when I was training stage2, the output of depth regress module is very small at the beginning(such as [0.11, -0.03,  0.43,....., 123]), it doesn't occur large numbers. Why? Look forward your reply.

**Comment by xingyizhou** [comment]
Hi, 
  Thanks for your interests in this project. This is caused the bug for PyTorch BN bug https://github.com/xingyizhou/pytorch-pose-hg-3d/issues/16 . Here are two solutions: 1). change pytorch version to 0.1.12. 2). Hack the source code of pytorch BN implementation (https://github.com/Microsoft/human-pose-estimation.pytorch): 
```
# PYTORCH=/path/to/pytorch
# for pytorch v0.4.0
sed -i "1194s/torch\.backends\.cudnn\.enabled/False/g" ${PYTORCH}/torch/nn/functional.py
# for pytorch v0.4.1
sed -i "1254s/torch\.backends\.cudnn\.enabled/False/g" ${PYTORCH}/torch/nn/functional.py
```

**Comment by xinghuokang** [comment]
Thanks for your reply quickly, I will try it. By the way, ECCV2018(Learning 3D Human Pose from Structure and Motion), the paper is researched on your network,  What do you think？

**Comment by xingyizhou** [comment]
It's good.
