### ISSUE TITLE
error occure while load stage 1 results

### ISSUE THREAD

**Issue by mahdiheybati73** [xingyizhou/pytorch-pose-hg-3d#45]
Hi 
I am new in pytorch, and i do not know how to load HGRegS2M2M2_60.t7. can you please help me to load heat maps ??

**Comment by xingyizhou** [comment]
Hi, 
  Here https://github.com/xingyizhou/pytorch-pose-hg-3d/blob/master/src/main.py#L23 is where the loading happens. And here https://github.com/xingyizhou/pytorch-pose-hg-3d/blob/master/src/train.py#L26 is the heatmap you want.

**Comment by xingyizhou** [comment]
No. You should do it yourself. The code is already there.

**Comment by xinghuoGitHub** [comment]
Thanks
