### ISSUE TITLE
Xorg memory leak

### ISSUE THREAD

**Issue by Peter654q** [xingyizhou/pytorch-pose-hg-3d#47]
Hi, 
I want to use your code to predict the coordinate of images, so I modify your demo code to make it save the pose information.
But I found that the Debugger() will cause Xorg memory leak.
Do you have any idea can help me to solve this problem?

Thanks!

**Comment by xingyizhou** [comment]
I honestly don't know what Xorg is and have no idea about the memory leak. Can you try removing the 3d plot part and use other 3d visualization tools for that?

**Comment by Peter654q** [comment]
Thanks for your reply!
I disable all plot function, now it can work.
