### ISSUE TITLE
the geometric constraint question

### ISSUE THREAD

**Issue by Keysmis** [xingyizhou/pytorch-pose-hg-3d#52]
![image](https://user-images.githubusercontent.com/9586803/50395411-c00fd100-079e-11e9-8ef1-3ee41825d6e2.png)
@xingyizhou ，您好，我在查看您的代码的时候，发现这里使用的计算bone length的时候，使用的似乎不是paper里说的2D pose的gt， 使用的似乎也是detect的2D pose？？

**Comment by xingyizhou** [comment]
Hi, 
  `xy = target[:, :, :2]` is the GT 2d pose. https://github.com/xingyizhou/pytorch-pose-hg-3d/blob/master/src/datasets/mpii.py#L54

**Comment by Keysmis** [comment]
Thanks for your answer, i will check it again.
