### ISSUE TITLE
Error in loading state_dict for PoseResNet

### ISSUE THREAD

**Issue by Peter654q** [xingyizhou/pytorch-pose-hg-3d#55]
Hi,
I want to use the weight I trained in stage 1 and continue training in stage 2, but it has runtime error.
RuntimeError: Error(s) in loading state_dict for PoseResNet:
	Missing key(s) in state_dict: "depth.weight", "depth.bias".
Do you have any idea can solve this problem?

Thanks!

**Comment by xingyizhou** [comment]
Hi, 
  Thanks for the report! I have fixed the problem https://github.com/xingyizhou/pytorch-pose-hg-3d/commit/b8afd1027f5e846e5923ac8deefafc76869ed788#diff-30a30f8b61024bfe24b090332ccda819R26 .

**Comment by Peter654q** [comment]
Thanks for your reply!
