### ISSUE TITLE
The architercure of PyTorch implementation

### ISSUE THREAD

**Issue by zhangyahu1** [xingyizhou/pytorch-pose-hg-3d#67]
Hi Xingyi,
I found the model architerture is different form your paper as you mentioned. Is it just one stack and one residual module followed by deconvoutional layers? and output 64*64*16(joint heatmaps) and 64*64*16(depth map)? Thanks!

**Comment by xingyizhou** [comment]
Hi, 
  No, it is not the hourglass architecture anymore, but just resnet50 at conv5 (32x downsample) with 3x deconv upsample (back to 4x downsample). You can refer to the Simple baseline paper for details.

**Comment by zhangyahu1** [comment]
Got it. Thanks for your answer!
