### ISSUE TITLE
two different way to calculate the root joint

### ISSUE THREAD

**Issue by DeepRunner** [xingyizhou/pytorch-pose-hg-3d#7]
It seems that the pts_3d[7]  is the spine and root joint in your code.
A) However, its position is calculated in two different way. 
one is the average of left shoulder and right shoulder , pts_3d[7] = (pts_3d[12] + pts_3d[13]) / 2
the other is the average of the neck and hip(pelvis),  p[i, 7] = (p[i, 6] + p[i, 8]) / 2.
I guess the latter is more reasonable because there seems no joint location is the average of the left shoulder and right shoulder. Is there some special consideration to do so?
Please see
[h36m.py](https://github.com/xingyizhou/pytorch-pose-hg-3d/blob/master/src/datasets/h36m.py#L67)
and [eval.py](https://github.com/xingyizhou/pytorch-pose-hg-3d/blob/master/src/utils/eval.py#L85)

B) It seems pts_3d[6] i.e. hip(pelvis) is a more commonly used root joint in other work of 3d human pose estimation. So I wonder why the pts_3d[7] i.e. spine is taken as root joint, is it because a better performance can be got in the experiment?

Thank you very much!

**Comment by DeepRunner** [comment]
It seems I have got the idea in your code now.
In pts_3d[7] = (pts_3d[12] + pts_3d[13]) / 2
pts_3d[7] is just a virtual root for training and just means the middle point of the left shoulder and right shoulder. 

In p[i, 7] = (p[i, 6] + p[i, 8]) / 2,
pts_3d[7] means the real spine for evaluation.However, its location is not inferred by the network so have to take the middle point of the neck and hip instead.

Am I correct about the different meaning of pts_3d[7] in your code?

Thanks!

**Comment by xingyizhou** [comment]
Yes, you are correct. The reason to do so is that the definition of torsor is different between MPII and H36M.

**Comment by DeepRunner** [comment]
Thanks!

**Comment by XiumeiChen** [comment]
Hi,DeepRunner.
Could you tell me where can I find the description of the Datasets? e.g. the serial numbers of the joints. I'm just confused about the data structure of the annotSampleTest.h5

Thank you very much.
Waiting for your help.
