### ISSUE TITLE
How is h36mSumLen = 4296 obtained?

### ISSUE THREAD

**Issue by NaveenSehgal** [xingyizhou/pytorch-pose-hg-3d#70]
From the paper, it should be the average bone length in the H36M dataset. So, I assume that the bone lengths are the euclidean distance between a pair of 3D points from joints that constitute a bone in `pytorch-pose-hg-3d/data/h36m/annotSampleTest.h5`, but what joints/bones are exactly included in this? The bone pairs I see thus far are as follows:

```
 (0, 1): l shin
 (1, 2): l thigh
 (3, 4): r thigh
 (4, 5): r shin
  
 (10, 11): r forearm
 (11, 12): r upper arm
 (13, 14): l upper arm
 (14, 15): l forearm
  
 (8, 12): r shoulder bone?
 (8, 13): l shoulder bone?
```

Eventually I want to test my own 3D dataset instead of H36M using this method, hence why I'm investigating all of the components that seem to be hard-coded for H36M. Thanks!

**Comment by xingyizhou** [comment]
Hi, 
  You can check https://github.com/xingyizhou/pytorch-pose-hg-3d/blob/master/src/lib/datasets/h36m_iccv.py#L96 . This is not carefully investigated.
