### ISSUE TITLE
depth coordinate

### ISSUE THREAD

**Issue by Ariel-JUAN** [xingyizhou/pytorch-pose-hg-3d#73]
Hi, I check the 3D coordinate in the annot_val.h5, it looks like this:
![image](https://user-images.githubusercontent.com/30546375/58544995-fad9d180-8234-11e9-97b0-0bff362de214.png)
So do we use meters to measure depth, 5567.62792969 equals 5.567m? Does it mean the absolute depth?
But I test demo.py, I got depth like this:
0.276933    0.16396    0.073877 .   -0.017895.......

I don't understand what do these depth values represent? Why there are negative numbers? 
Thanks.

**Comment by sunmengnan** [comment]
> Hi, I check the 3D coordinate in the annot_val.h5, it looks like this: ![image](https://user-images.githubusercontent.com/30546375/58544995-fad9d180-8234-11e9-97b0-0bff362de214.png) So do we use meters to measure depth, 5567.62792969 equals 5.567m? Does it mean the absolute depth? But I test demo.py, I got depth like this: 0.276933 0.16396 0.073877 . -0.017895.......
> 
> I don't understand what do these depth values represent? Why there are negative numbers? Thanks.

Have you solved?
