### ISSUE TITLE
Gaussian kernel generation

### ISSUE THREAD

**Issue by blackccpie** [xingyizhou/pytorch-pose-hg-3d#74]
Hi,

I was just wondering how you generated your hardcoded 7x7 gaussian kernel in [img.py](https://github.com/xingyizhou/pytorch-pose-hg-3d/blob/2D/src/utils/img.py).
In fact the values differ from the reference formula found in the reference `pose-hg-train` [implementation](https://github.com/princeton-vl/pose-hg-train/blob/master/src/pypose/draw.py), which is something like:

```python
# The gaussian is not normalized, we want the center value to equal 1
g = np.exp(- ((x - x0) ** 2 + (y - y0) ** 2) / (2 * sigma ** 2))
```

Thanks for your help,

Regards

Albert

**Comment by xingyizhou** [comment]
I am aware of the difference, and that's why I use hard coding. The value is from my original [torch implementation](https://github.com/xingyizhou/pose-hg-3d/blob/master/src/util/img.lua#L296).

**Comment by blackccpie** [comment]
ok thanks for the tip, the original torch.image native implementation of image.gaussian can be found [here](https://github.com/torch/image/blob/5aa18819b6a7b44751f8a858bd232d1c07b67985/generic/image.c#L1981), and it gives the sames coefficients as yours.
